### PR TITLE
AzureDevOps: Feature - Add "add attachments" function. Implement test connectivity.

### PR DESCRIPTION
**Pull request by import-au**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [x] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Adding the add attachment action. Documentation here: https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/attachments/create?view=azure-devops-rest-7.1&tabs=HTTP
- Implementing the test connectivity function. Action was not implemented.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- See Release Notes section

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by achandya-crest** [comment]
Hello @import-au, I have a few queries.

1. I observed that the filename parameter is not used anywhere in the action here: https://github.com/import-au/azuredevops/commit/f3c237059dfe817ddd6ffc326c81c3a47de7f2b8#diff-51d14845ae3d86b0f4fd87e073247a9cba085e521e70b8cfb322897ed0adb796R446
I have changed the code and passed the filename in vault_info() according to my understanding. Could you please check?

2. We are changing the min_phantom_version to 5.5.0. Is it fine for you?

3. I observed that the column_name and column_order are the same for a few data paths in output of add_attachment action in JSON. Could you please tell me which fields do you want us to display in the output table?

**Comment by achandya-crest** [comment]
@import-au, Any update on https://github.com/splunk-soar-connectors/azuredevops/pull/6#issuecomment-1448582393?

**Comment by import-au** [comment]
Hey, sorry. This account is associated with an email address I don't check often enough.

1. Good catch. This is supposed to be appeneded to the query string parameters so a complete request would be:`/_apis/wit/attachments?api-version=7.1-preview.3&fileName=screenshot.png`
2. My instance is 5.3.2, so I would have to do the download and change version hack to use this app.
3. Should only need the attachment url for that action.

Unrelated to your questions, I think I introduced a breaking bug in my make rest call code here
https://github.com/splunk-soar-connectors/azuredevops/pull/6/commits/f3c237059dfe817ddd6ffc326c81c3a47de7f2b8#diff-51d14845ae3d86b0f4fd87e073247a9cba085e521e70b8cfb322897ed0adb796R151-R160 This is no longer dynamically taking the `api-version` from the action as an override to the app config. Not sure the best way to approach this long term since every API has a different supported version.

**Comment by achandya-crest** [comment]
Thanks for the update @import-au. As you mentioned the changes related to filename parameter usage and the bug that was introduced in make_rest_call, can you please make the code changes? Please update us once all the changes are done.

**Comment by import-au** [comment]
@achandya-crest I implemented a fix that seems to work, not sure if it's the best way to handle it or not. I also implemented the filename parameter and cleaned up the add_attachments output.

Let me know if anything stands out.

**Comment by achandya-crest** [comment]
Hello @import-au, Shall we move forward with the release of the current code considering no changes are required?

**Comment by achandya-crest** [comment]
Hey @import-au, Shall we move forward with the release of changes that are present right now in this PR?

**Comment by achandya-crest** [comment]
Hello @import-au, Do you want to add value_list in api_version parameter in config back as suggested by me or shall we proceed with the current changes?

**Comment by import-au** [comment]
@achandya-crest I added it to this action because it's a newer action than what is supported in the value list, I made it a text box because Microsoft keeps updating/changing the version and I didn't want to have to release a new app version every time Microsoft updated the API Version. I am fine with it as it exists right now but happy to discuss feedback.

**Review by mishalp-crest — APPROVED** [review]

**Review by ighelani-crest — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
